name: leetcode_companion_app
description: Leetcode companion app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0-beta.24+1
  go_router: ^10.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0

  leetcode_api_dart:
    path: ../leetcode_api_dart
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  provider: ^6.0.5
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  uses-material-design: true
